use serde::Serialize;

use crate::observability::contract::{
    AdapterLifecycleState, ContractEvent, DispatchOutcomeClass, OrganResponseStatus,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EventLevel {
    Info,
    Warn,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct FlatContractEvent {
    pub(crate) level: EventLevel,
    pub(crate) subsystem: &'static str,
    pub(crate) family: &'static str,
    pub(crate) run_id: String,
    pub(crate) tick: u64,
    pub(crate) organ_id: Option<String>,
    pub(crate) thread_id: Option<String>,
    pub(crate) turn_id: Option<String>,
    pub(crate) request_id: Option<String>,
    pub(crate) endpoint_id: Option<String>,
    pub(crate) descriptor_id: Option<String>,
    pub(crate) act_id: Option<String>,
    pub(crate) sense_id: Option<String>,
    pub(crate) adapter_id: Option<String>,
    pub(crate) adapter_type: Option<String>,
    pub(crate) transition_kind: Option<String>,
    pub(crate) outcome: Option<String>,
    pub(crate) direction: Option<String>,
    pub(crate) binding_kind: Option<String>,
    pub(crate) change_mode: Option<String>,
    pub(crate) state: Option<String>,
    pub(crate) kind: Option<String>,
}

pub(crate) fn flatten_contract_event(event: &ContractEvent) -> FlatContractEvent {
    let subsystem = event.subsystem().prefix();
    let family = event.family();

    match event {
        ContractEvent::AiGatewayRequest(item) => FlatContractEvent {
            level: level_from_optional_error(item.error_when_present.as_ref()),
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: item.organ_id_when_present.clone(),
            thread_id: item.thread_id_when_present.clone(),
            turn_id: item.turn_id_when_present.map(|value| value.to_string()),
            request_id: Some(item.request_id.clone()),
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: Some(item.kind.clone()),
        },
        ContractEvent::AiGatewayTurn(item) => FlatContractEvent {
            level: if item.status == "error" {
                EventLevel::Warn
            } else {
                EventLevel::Info
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: item.organ_id_when_present.clone(),
            thread_id: Some(item.thread_id.clone()),
            turn_id: Some(item.turn_id.to_string()),
            request_id: item.request_id_when_present.clone(),
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: Some(item.status.clone()),
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: None,
        },
        ContractEvent::AiGatewayThread(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: item.organ_id_when_present.clone(),
            thread_id: Some(item.thread_id.clone()),
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: Some(item.kind.clone()),
        },
        ContractEvent::CortexTick(item) => FlatContractEvent {
            level: level_from_optional_error(item.error_when_present.as_ref()),
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: Some(item.kind_or_status.clone()),
            kind: Some(item.kind_or_status.clone()),
        },
        ContractEvent::CortexOrgan(item) => FlatContractEvent {
            level: match item.status {
                OrganResponseStatus::Error => EventLevel::Warn,
                OrganResponseStatus::Ok => EventLevel::Info,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: Some(item.organ_id.clone()),
            thread_id: item.thread_id_when_present.clone(),
            turn_id: item.turn_id_when_present.map(|value| value.to_string()),
            request_id: Some(item.request_id.clone()),
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: Some(enum_label(item.status)),
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: Some(item.phase.clone()),
            kind: Some(item.phase.clone()),
        },
        ContractEvent::CortexGoalForest(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: Some(item.kind.clone()),
        },
        ContractEvent::StemTick(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: Some(item.status.clone()),
            kind: Some(item.status.clone()),
        },
        ContractEvent::StemSignal(item) => FlatContractEvent {
            level: if item.reason_when_present.is_some() {
                EventLevel::Warn
            } else {
                EventLevel::Info
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: item.endpoint_id_when_present.clone(),
            descriptor_id: Some(item.descriptor_id.clone()),
            act_id: item.act_id_when_present.clone(),
            sense_id: item.sense_id_when_present.clone(),
            adapter_id: None,
            adapter_type: None,
            transition_kind: Some(enum_label(item.transition_kind)),
            outcome: None,
            direction: Some(enum_label(item.direction)),
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: None,
        },
        ContractEvent::StemDispatch(item) => FlatContractEvent {
            level: match item.terminal_outcome_when_present {
                Some(DispatchOutcomeClass::Rejected | DispatchOutcomeClass::Lost) => {
                    EventLevel::Warn
                }
                _ => EventLevel::Info,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: item.endpoint_id_when_present.clone(),
            descriptor_id: item.descriptor_id_when_present.clone(),
            act_id: Some(item.act_id.clone()),
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: item.terminal_outcome_when_present.map(enum_label),
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: Some(item.kind.clone()),
        },
        ContractEvent::StemProprioception(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: Some(item.kind.clone()),
        },
        ContractEvent::StemDescriptorCatalog(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: Some(enum_label(item.change_mode)),
            state: Some(item.catalog_version.clone()),
            kind: None,
        },
        ContractEvent::StemAfferentRule(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: Some(item.rule_id.clone()),
            kind: Some(item.kind.clone()),
        },
        ContractEvent::SpineAdapter(item) => FlatContractEvent {
            level: match item.kind_or_state {
                AdapterLifecycleState::Faulted => EventLevel::Warn,
                _ => EventLevel::Info,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: Some(item.adapter_id.clone()),
            adapter_type: Some(item.adapter_type.clone()),
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: Some(enum_label(item.kind_or_state)),
            kind: None,
        },
        ContractEvent::SpineEndpoint(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: Some(item.endpoint_id.clone()),
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: item.adapter_id_when_present.clone(),
            adapter_type: None,
            transition_kind: Some(enum_label(item.kind_or_transition)),
            outcome: None,
            direction: None,
            binding_kind: None,
            change_mode: None,
            state: None,
            kind: None,
        },
        ContractEvent::SpineDispatch(item) => FlatContractEvent {
            level: match item.outcome_when_present {
                Some(DispatchOutcomeClass::Rejected | DispatchOutcomeClass::Lost) => {
                    EventLevel::Warn
                }
                _ => EventLevel::Info,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick,
            organ_id: None,
            thread_id: None,
            turn_id: None,
            request_id: None,
            endpoint_id: Some(item.endpoint_id.clone()),
            descriptor_id: item.descriptor_id_when_present.clone(),
            act_id: Some(item.act_id.clone()),
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: item.outcome_when_present.map(enum_label),
            direction: None,
            binding_kind: item.binding_kind_when_present.clone(),
            change_mode: None,
            state: None,
            kind: Some(item.kind.clone()),
        },
    }
}

fn level_from_optional_error(value: Option<&serde_json::Value>) -> EventLevel {
    if value.is_some() {
        EventLevel::Warn
    } else {
        EventLevel::Info
    }
}

fn enum_label<T>(value: T) -> String
where
    T: Serialize,
{
    serde_json::to_value(value)
        .ok()
        .and_then(|value| value.as_str().map(str::to_string))
        .unwrap_or_default()
}
