use serde::Serialize;

use crate::observability::contract::{
    AdapterLifecycleState, ContractEvent, DispatchOutcomeClass, OrganResponseStatus,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EventLevel {
    Info,
    Warn,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct FlatContractEvent {
    pub(crate) level: EventLevel,
    pub(crate) subsystem: &'static str,
    pub(crate) family: &'static str,
    pub(crate) run_id: String,
    pub(crate) tick: Option<u64>,
    pub(crate) stage: Option<String>,
    pub(crate) route_or_organ: Option<String>,
    pub(crate) request_id: Option<String>,
    pub(crate) endpoint_id: Option<String>,
    pub(crate) descriptor_id: Option<String>,
    pub(crate) act_id: Option<String>,
    pub(crate) sense_id: Option<String>,
    pub(crate) adapter_id: Option<String>,
    pub(crate) adapter_type: Option<String>,
    pub(crate) transition_kind: Option<String>,
    pub(crate) outcome: Option<String>,
    pub(crate) direction: Option<String>,
    pub(crate) binding_target: Option<String>,
    pub(crate) change_mode: Option<String>,
    pub(crate) state: Option<String>,
}

pub(crate) fn flatten_contract_event(event: &ContractEvent) -> FlatContractEvent {
    let subsystem = event.subsystem().prefix();
    let family = event.family();

    match event {
        ContractEvent::CortexTick(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: Some(item.tick),
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_target: None,
            change_mode: None,
            state: None,
        },
        ContractEvent::CortexOrganRequest(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: Some(item.tick),
            stage: Some(item.stage.clone()),
            route_or_organ: Some(item.route_or_organ.clone()),
            request_id: Some(item.request_id.clone()),
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_target: None,
            change_mode: None,
            state: None,
        },
        ContractEvent::CortexOrganResponse(item) => FlatContractEvent {
            level: match item.status {
                OrganResponseStatus::Ok => EventLevel::Info,
                OrganResponseStatus::Error => EventLevel::Warn,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: Some(item.tick),
            stage: Some(item.stage.clone()),
            route_or_organ: None,
            request_id: Some(item.request_id.clone()),
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: Some(enum_label(item.status)),
            direction: None,
            binding_target: None,
            change_mode: None,
            state: None,
        },
        ContractEvent::CortexGoalForestSnapshot(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: Some(item.tick),
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_target: None,
            change_mode: None,
            state: None,
        },
        ContractEvent::StemSignalTransition(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick_when_known,
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: item.endpoint_id.clone(),
            descriptor_id: Some(item.descriptor_id.clone()),
            act_id: item.act_id.clone(),
            sense_id: item.sense_id.clone(),
            adapter_id: None,
            adapter_type: None,
            transition_kind: Some(enum_label(item.transition_kind)),
            outcome: None,
            direction: Some(enum_label(item.direction)),
            binding_target: None,
            change_mode: None,
            state: None,
        },
        ContractEvent::StemDispatchTransition(item) => FlatContractEvent {
            level: match item.terminal_outcome_when_present {
                Some(DispatchOutcomeClass::Rejected | DispatchOutcomeClass::Lost) => {
                    EventLevel::Warn
                }
                _ => EventLevel::Info,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick_when_known,
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: Some(item.act_id.clone()),
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: Some(enum_label(item.transition_kind)),
            outcome: item.terminal_outcome_when_present.map(enum_label),
            direction: None,
            binding_target: None,
            change_mode: None,
            state: None,
        },
        ContractEvent::StemDescriptorCatalog(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: None,
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_target: None,
            change_mode: Some(enum_label(item.change_mode)),
            state: Some(item.catalog_version.clone()),
        },
        ContractEvent::SpineAdapterLifecycle(item) => FlatContractEvent {
            level: match item.state_transition {
                AdapterLifecycleState::Faulted => EventLevel::Warn,
                _ => EventLevel::Info,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: None,
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: Some(item.adapter_id.clone()),
            adapter_type: Some(item.adapter_type.clone()),
            transition_kind: None,
            outcome: None,
            direction: None,
            binding_target: None,
            change_mode: None,
            state: Some(enum_label(item.state_transition)),
        },
        ContractEvent::SpineEndpointLifecycle(item) => FlatContractEvent {
            level: EventLevel::Info,
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: None,
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: Some(item.endpoint_id.clone()),
            descriptor_id: None,
            act_id: None,
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: Some(enum_label(item.transition_kind)),
            outcome: None,
            direction: None,
            binding_target: None,
            change_mode: None,
            state: None,
        },
        ContractEvent::SpineDispatchOutcome(item) => FlatContractEvent {
            level: match item.outcome {
                DispatchOutcomeClass::Acknowledged => EventLevel::Info,
                DispatchOutcomeClass::Rejected | DispatchOutcomeClass::Lost => EventLevel::Warn,
            },
            subsystem,
            family,
            run_id: item.run_id.clone(),
            tick: item.tick_when_known,
            stage: None,
            route_or_organ: None,
            request_id: None,
            endpoint_id: None,
            descriptor_id: item.descriptor_id_when_present.clone(),
            act_id: Some(item.act_id.clone()),
            sense_id: None,
            adapter_id: None,
            adapter_type: None,
            transition_kind: None,
            outcome: Some(enum_label(item.outcome)),
            direction: None,
            binding_target: Some(item.binding_target.clone()),
            change_mode: None,
            state: None,
        },
    }
}

fn enum_label<T>(value: T) -> String
where
    T: Serialize,
{
    serde_json::to_value(value)
        .ok()
        .and_then(|value| value.as_str().map(str::to_string))
        .unwrap_or_default()
}
